### ISSUE TITLE
Feature Request: Ability to add a custom name to sensor

### ISSUE THREAD

**Issue by ekkesa** [BitFetch/bitfetch-home-assistant#1]
Ability to add a custom name to sensor

E.g:
```
sensor:
  - platform: bitfetch
    name: Current Bitcoin Price
    pair: BTCUSD
    api_key: !secret BitFetchAPIKey
    scan_interval: 300
```
